name: Calculator Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Post Deployment Message
        run: echo "Application deployed successfully to production!"
        
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker Image
        run: docker build -t calculator:V2 .  

      - name: Run Docker Container
        run: docker run -d --name calculator003 -p 3000:3000 calculator:V2 

      - name: Verify Application is Running
        run: |
          sleep 10  # Wait for the container to start
          if curl -s http://localhost:3000 | grep -q "Calculator"; then
            echo "Application is running successfully in Docker container.";
          else
            echo "Application failed to start in Docker container.";
            exit 1;
          fi
          
      - name: Clean Up Docker Container
        run: docker rm -f calculator003
          